config.skip_core_tasks = true

[tasks.build]
  command = "cargo"
  args    = ["build"]

[tasks.test]
  command = "cargo"
  args    = ["test"]

[tasks.release]
  command = "cargo"
  args    = ["build", "--release"]

[tasks.prebuild]
  dependencies = ["format", "lint"]

[tasks.check]
  dependencies = ["format", "lint"]

[tasks.format]
  command = "cargo"
  args    = ["fmt"]
  env     = { RUSTUP_TOOLCHAIN = "nightly" }

[tasks.lint]
  command = "cargo"
  args    = ["clippy"]

[tasks."lint:fix"]
  command = "cargo"
  args    = ["clippy", "--fix", "--allow-dirty"]

[tasks.coverage]
  command = "cargo"
  args    = ["llvm-cov", "--summary-only", "--branch"]
  env     = { RUSTUP_TOOLCHAIN = "nightly" }

[tasks."coverage:html"]
  command = "cargo"
  args    = ["llvm-cov", "--html", "--output-dir=coverage", "--branch"]
  env     = { RUSTUP_TOOLCHAIN = "nightly" }
