name: Run Tests
on:
  push:
    branches:
      - main
      - v1.x
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    name: Sanity Check
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-make
        run: cargo install cargo-make
      - name: Run checks
        run: cargo make prebuild
